AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the infrastructure for Life Dashboard

Parameters:
  GatewayName:
    Type: String
    Default: WebhookGateway

  GatewayStageName:
    Type: String
    Default: dev

  GatewayHTTPMethod:
    Type: String
    Default: POST

  WebhookLambdaFunctionName:
    Type: String
    Default: webhook

  RequestLambdaFunctionName:
    Type: String
    Default: request

  DBInstanceID:
    Type: String
    Default: lifedbinstance

  DBName:
    Type: String
    Default: lifedb

  DBInstanceClass:
    Type: String
    Default: db.t2.micro

  DBAllocatedStorage:
    Type: Number
    Default: '20'

  DBUsername:
    NoEcho: 'true'
    Type: String
    Default: admin

  DBPassword:
    NoEcho: 'true'
    Type: String
    Default: password
  
  # UpAPIKey:
  #   NoEcho: 'true'
  #   Type: String
  
  # SpotifyAPIKey:
  #   NoEcho: 'true'
  #   Type: String

  # TrelloAPIKey:
  #   NoEcho: 'true'
  #   Type: String
  

Resources:
  ## IAM Roles
  WebhookLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Effect: Allow
            Resource:
              - '*' 

  RequestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Effect: Allow
            Resource:
              - '*'
  ## Log Groups
  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WebhookLambdaFunctionName}
      RetentionInDays: 90
  
  RequestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RequestLambdaFunctionName}
      RetentionInDays: 90

  ## Lambdas
  WebhookApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WebhookLambdaFunction.Arn
      Principal: apigateway.amazonaws.com

  WebhookLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Receives POST request via webhook
      FunctionName: !Ref WebhookLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt WebhookLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetA, !Ref PrivateSubnetB] 
  
  RequestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Makes a GET call to a public API
      FunctionName: !Ref RequestLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt RequestLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref PrivateSubnetA, !Ref PrivateSubnetB] 

  # API Gateways  
  WebhookGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref GatewayName
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: Gateway to process webhook requests

  WebhookGatewayGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: !Ref GatewayHTTPMethod
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookLambdaArn}/invocations
          - WebhookLambdaArn: !GetAtt WebhookLambdaFunction.Arn
      ResourceId: !GetAtt WebhookGateway.RootResourceId
      RestApiId: !Ref WebhookGateway

  WebhookGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WebhookGatewayGetMethod
    Properties:
      RestApiId: !Ref WebhookGateway
      StageName: !Ref GatewayStageName

  # Networking
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: LifeDashboardVPC
  
  LifeDashboardVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 10.1.0.0/16
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref LifeDashboardVPC
  
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.50.0/24
      VpcId: !Ref LifeDashboardVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-PrivateA
  
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.60.0/24
      VpcId: !Ref LifeDashboardVPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-PrivateB
  
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.10.0/24
      VpcId: !Ref LifeDashboardVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-PublicA
  
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.20.0/24
      VpcId: !Ref LifeDashboardVPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-PublicB


  
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: LifeDashboardVPC
  
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LifeDashboardVPC
      Tags:
      - Key: Name
        Value: Public
  
  PublicRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/16
      GatewayId: !Ref InternetGateway
  
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LifeDashboardVPC
      Tags:
      - Key: Name
        Value: Private
  
  PrivateRoute1:
    Type: AWS::EC2::Route
    DependsOn: PrivateRouteTable
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnetA
      Tags:
      - Key: Name
        Value: !Sub NAT-${AWS::StackName}
  
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  
  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: PrivateRouteTable
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable
  
  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable
  
  
      
  

  
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref LifeDashboardVPC
      GroupDescription: Ingress/Egress rules for the lambdas
      SecurityGroupIngress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
        ToPort: -1
        FromPort: -1
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
        ToPort: -1
        FromPort: -1


  

  
  ## TODO: Route Table
  ## TODO: NAT Instance
  ## TODO: Public/Private subnets (connect one subnet to the IG)


  # Database
  # LifeDatabase:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     DBInstanceIdentifier: !Ref DBInstanceID
  #     DBName: !Ref DBName
  #     DBInstanceClass: !Ref DBInstanceClass
  #     AllocatedStorage: !Ref DBAllocatedStorage
  #     Engine: MySQL
  #     EngineVersion: 8.0.16
  #     MasterUsername: !Ref DBUsername
  #     MasterUserPassword: !Ref DBPassword
  #     DBSubnetGroupName: !Ref DBSubnetGroup
    # DBSubnetGroup:
  #   Type: AWS::RDS::DBSubnetGroup
  #   Properties:
  #     SubnetIds:
  #       - !Ref Subnet1
  #       - !Ref Subnet2
  #     DBSubnetGroupDescription: Subnet group for MySQL instance
  
  



Outputs:
  WebhookGatewayInvokeURL:
    Value: !Sub https://${WebhookGateway}.execute-api.${AWS::Region}.amazonaws.com/${GatewayStageName}
  
  WebhookLambdaArn:
    Value: !GetAtt WebhookLambdaFunction.Arn
    