AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the infrastructure for Life Dashboard

Parameters:
  GatewayName:
    Type: String
    Default: WebhookGateway

  GatewayStageName:
    Type: String
    Default: dev

  GatewayHTTPMethod:
    Type: String
    Default: POST

  WebhookLambdaFunctionName:
    Type: String
    Default: webhook

  RequestLambdaFunctionName:
    Type: String
    Default: request

  DBInstanceID:
    Type: String
    Default: lifedbinstance

  DBName:
    Type: String
    Default: lifedb

  DBInstanceClass:
    Type: String
    Default: db.t2.micro

  DBAllocatedStorage:
    Type: Number
    Default: '20'

  DBUsername:
    NoEcho: 'true'
    Type: String
    Default: admin

  DBPassword:
    NoEcho: 'true'
    Type: String
    Default: password
  
  # UpAPIKey:
  #   NoEcho: 'true'
  #   Type: String
  
  # SpotifyAPIKey:
  #   NoEcho: 'true'
  #   Type: String

  # TrelloAPIKey:
  #   NoEcho: 'true'
  #   Type: String
  

Resources:
  ## IAM Roles
  WebhookLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Effect: Allow
            Resource:
              - '*' 

  RequestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Effect: Allow
            Resource:
              - '*'
  ## Log Groups
  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WebhookLambdaFunctionName}
      RetentionInDays: 90
  
  RequestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RequestLambdaFunctionName}
      RetentionInDays: 90

  ## Lambdas
  WebhookApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WebhookLambdaFunction.Arn
      Principal: apigateway.amazonaws.com

  WebhookLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Receives POST request via webhook
      FunctionName: !Ref WebhookLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt WebhookLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref Subnet1, !Ref Subnet2] 
  
  RequestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Makes a GET call to a public API
      FunctionName: !Ref RequestLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt RequestLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]
      VpcConfig:
        SecurityGroupIds: [!Ref LambdaSecurityGroup]
        SubnetIds: [!Ref Subnet1, !Ref Subnet2] 

  # API Gateways  
  WebhookGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref GatewayName
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: Gateway to process webhook requests

  WebhookGatewayGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: !Ref GatewayHTTPMethod
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookLambdaArn}/invocations
          - WebhookLambdaArn: !GetAtt WebhookLambdaFunction.Arn
      ResourceId: !GetAtt WebhookGateway.RootResourceId
      RestApiId: !Ref WebhookGateway

  WebhookGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WebhookGatewayGetMethod
    Properties:
      RestApiId: !Ref WebhookGateway
      StageName: !Ref GatewayStageName

  # Networking
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      AvailabilityZone: ap-southeast-2a
  
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC
      AvailabilityZone: ap-southeast-2b
  
  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      VpcId: !Ref VPC
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      DBSubnetGroupDescription: Subnet group for MySQL instance
  
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Ingress/Egress rules for the lambdas
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        ToPort: 80
        FromPort: 80
      SecurityGroupEgress:
      - IpProtocol: tcp
        CidrIp: 0.0.0.0/0
        ToPort: 80
        FromPort: 80

  LambdaRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  
  LambdaNATRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref LambdaRouteTable
      InstanceId: !Ref NATInstance
      DestinationCidrBlock: 0.0.0.0/0


  

  
  ## TODO: Route Table
  ## TODO: NAT Instance
  ## TODO: Public/Private subnets (connect one subnet to the IG)


  # Database
  LifeDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
  
  
  ## NAT
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref NATInstance
  


  NatSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Ingress/Egress rules for the NAT instance
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 10.0.0.0/16
        FromPort: 80
        ToPort: 80
      - IpProtocol: tcp
        CidrIp: 10.0.0.0/16
        FromPort: 443
        ToPort: 443
      - IpProtocol: udp
        CidrIp: 0.0.0.0/0
        FromPort: 123
        ToPort: 123
      SecurityGroupEgress:
      - IpProtocol: udp
        FromPort: 123
        ToPort: 123
        CidrIp: 10.0.0.0/16
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 10.0.0.0/16
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 10.0.0.0/16

  NATIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'ec2.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: ec2
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: Stmt1425023276000
            Effect: Allow
            Action:
            - 'ec2:AssociateAddress'
            - 'ec2:ModifyInstanceAttribute'
            - 'ec2:CreateRoute'
            - 'ec2:ReplaceRoute'
            Resource:
            - '*'
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            - 'logs:DescribeLogStreams'
            Resource: !GetAtt RequestLogGroup.Arn
  
  NATInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-002519e717bb4797a
      InstanceType: t2.small
      SecurityGroupIds: [!Ref NatSecurityGroup]
      SubnetId: !Ref Subnet3

  



Outputs:
  WebhookGatewayInvokeURL:
    Value: !Sub https://${WebhookGateway}.execute-api.${AWS::Region}.amazonaws.com/${GatewayStageName}
  
  WebhookLambdaArn:
    Value: !GetAtt WebhookLambdaFunction.Arn
    