AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the infrastructure for Life Dashboard

Parameters:
  GatewayName:
    Type: String
    Default: WebhookGateway

  GatewayStageName:
    Type: String
    Default: dev

  GatewayHTTPMethod:
    Type: String
    Default: POST
  

Resources:
## IAM
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            - s3:*
            - codepipeline:PutJobSuccessResult
            - codepipeline:PutJobFailureResult
            Effect: Allow
            Resource:
              - '*' 


## LOG GROUP
  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/webhookfunction
      RetentionInDays: 90
  
## LAMBDA
  WebhookApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WebhookLambdaFunction.Arn
      Principal: apigateway.amazonaws.com

  WebhookLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Receives POST request via webhook
      FunctionName: WebhookLambda
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7


## API GATEWAY
  WebhookGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref GatewayName
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: Gateway to process webhook requests

  WebhookGatewayGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: !Ref GatewayHTTPMethod
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookLambdaArn}/invocations
          - WebhookLambdaArn: !GetAtt WebhookLambdaFunction.Arn
      ResourceId: !GetAtt WebhookGateway.RootResourceId
      RestApiId: !Ref WebhookGateway

  WebhookGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WebhookGatewayGetMethod
    Properties:
      RestApiId: !Ref WebhookGateway
      StageName: !Ref GatewayStageName

  FinanceCsvBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: financebucket-007576465237




Outputs:
  WebhookGatewayInvokeURL:
    Value: !Sub https://${WebhookGateway}.execute-api.${AWS::Region}.amazonaws.com/${GatewayStageName}
  
  WebhookLambdaArn:
    Value: !GetAtt WebhookLambdaFunction.Arn
    