AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the infrastructure for Life Dashboard

Parameters:
  GatewayName:
    Type: String
    Default: WebhookGateway

  GatewayStageName:
    Type: String
    Default: dev

  GatewayHTTPMethod:
    Type: String
    Default: POST

  WebhookLambdaFunctionName:
    Type: String
    Default: webhook

  RequestLambdaFunctionName:
    Type: String
    Default: request

  DBInstanceID:
    Type: String
    Default: lifedbinstance

  DBName:
    Type: String
    Default: lifedb

  DBInstanceClass:
    Type: String
    Default: db.t2.micro

  DBAllocatedStorage:
    Type: Number
    Default: '20'

  DBUsername:
    NoEcho: 'true'
    Type: String
    Default: admin

  DBPassword:
    NoEcho: 'true'
    Type: String
    Default: password
  
  

Resources:
  ## IAM Role
  WebhookLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${WebhookLambdaFunctionName}:*

  RequestLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${RequestLambdaFunctionName}:*

  ## Log Group
  WebhookLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WebhookLambdaFunctionName}
      RetentionInDays: 90
  
  RequestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RequestLambdaFunctionName}
      RetentionInDays: 90

  ## Lambda
  WebhookApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WebhookLambdaFunction.Arn
      Principal: apigateway.amazonaws.com

  WebhookLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Receives POST request via webhook
      FunctionName: !Ref WebhookLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt WebhookLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]
  
  RequestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            return {
              'body': 'Hello there {0}'.format(event['requestContext']['identity']['sourceIp']),
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: Makes a GET call to a public API
      FunctionName: !Ref RequestLambdaFunctionName
      Handler: index.handler
      Role: !GetAtt RequestLambdaRole.Arn
      Runtime: python3.7
      Layers: [arn:aws:lambda:ap-southeast-2:007576465237:layer:requests-python-layer:1]

  # API Gateways  
  WebhookGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref GatewayName
      EndpointConfiguration:
        Types:
          - REGIONAL
      Description: Gateway to process webhook requests

  WebhookGatewayGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: !Ref GatewayHTTPMethod
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookLambdaArn}/invocations
          - WebhookLambdaArn: !GetAtt WebhookLambdaFunction.Arn
      ResourceId: !GetAtt WebhookGateway.RootResourceId
      RestApiId: !Ref WebhookGateway

  WebhookGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WebhookGatewayGetMethod
    Properties:
      RestApiId: !Ref WebhookGateway
      StageName: !Ref GatewayStageName

  # Networking
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      AvailabilityZone: ap-southeast-2a
  
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC
      AvailabilityZone: ap-southeast-2b
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      DBSubnetGroupDescription: Subnet group for MySQL instance
  
  ## TODO: Security Groups
  ## TODO: Route Table
  ## TODO: NAT Instance
  ## TODO: Public/Private subnets (connect one subnet to the IG)


  # Database
  LifeDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
  




Outputs:
  WebhookGatewayInvokeURL:
    Value: !Sub https://${WebhookGateway}.execute-api.${AWS::Region}.amazonaws.com/${GatewayStageName}
  
  WebhookLambdaArn:
    Value: !GetAtt WebhookLambdaFunction.Arn
    